### ISSUE TITLE
Endpoint requires instance discriminator even when only replying to a callback

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.Callbacks#24]
Currently, adding the Callbacks package to a project requires you to set an instance discriminator (https://github.com/Particular/NServiceBus.Callbacks/blob/develop/src/NServiceBus.Callbacks/CallbackSupport.cs#L16).

Since both the requesting and replying endpoints need the package installed, this means that both endpoints must have an instance discriminator set, which includes the overhead of an extra queue/messagepump.

Only the requesting endpoint actually needs this extra queue, so could we move this check to somewhere that would only be checked if the endpoint is going to request a callback?

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers should we consider this for https://github.com/Particular/PlatformDevelopment/issues/734 ?

**Comment by andreasohlund** [comment]
>Since both the requesting and replying endpoints need the package installedSince both the requesting and replying endpoints need the package installed

This sounds off, doesn't the replying endpoint do a plain `context.Reply`?

**Comment by danielmarbach** [comment]
If I recall correctly the package only needs to be installed on the replier side if you are sending things like enums and ints.

**Comment by bording** [comment]
> If I recall correctly the package only needs to be installed on the replier side if you are sending things like enums and ints.

This was what I was thinking as well. If that's not true and you never need the package installed to be able to reply, then we can close the issue!

**Comment by andreasohlund** [comment]
Ah, I think that is correct. So we need to either:

1. Switch to a runtime check 
2. Provide an some config option to ".ThisEndpointWillOnlyReplyToCallbacksSoHelpMeGod()"

**Comment by bording** [comment]
Using the callbacks sample, I just verified that the package is needed for enum and int replies.

>Ah, I think that is correct. So we need to either:

>1. Switch to a runtime check
>2. Provide an some config option to ".ThisEndpointWillOnlyReplyToCallbacksSoHelpMeGod()"

Those were the two options I was thinking of as well. Though even with option 2, it would be nice if we could check for the option and prevent `Request` from being called.

**Comment by danielmarbach** [comment]
Well there are more options:

1. Move the enum and int support into a dedicated package under something like NServiceBus.Callbacks.EnumIntReply which allows users to pull this in only
1. Sneak the functionality into the core which silently behind the scenes enables itself when the callbacks feature is present

**Comment by timbussmann** [comment]
why does the callbacks always needs an instance discriminator anyways? I assume the check is to prevent runtume exceptions occuring when using `RouteReplyToThisInstance` (pure assumption, did not check the code)? Should the callbacks package detect whether the endpoint using callbacks is using scaleout configuration first?

**Comment by bording** [comment]
> Sneak the functionality into the core which silently behind the scenes enables itself when the callbacks feature is present

Of the options mentioned so far, I think this might be the best one from an end user standpoint. No additional work to maintain a separate package that we'd then have to explain when to use it. It also simplifies the story around when to use the Callbacks package: include when you need to Request.

**Comment by bording** [comment]
> why does the callbacks always needs an instance discriminator anyways?

It's required because that guarantees there is an instance-specific queue around to be able to route to.  For transports that support native competing consumers without an instance discriminator (for example, rabbit) you'd have no way of routing back to a single instance in all cases otherwise.

Even if you just had one instance, it would be dangerous to relax the restriction, because another endpoint could be added to the queue at any time, and then callbacks would silently start failing.

**Comment by andreasohlund** [comment]
I agree that a additional package seems to be overkill, but sneaking some parts of the callback back into the core seems like step in the wrong direction? (we've gone to great lengths to get it out of the core)

I vote for a runtime check in `.Request` instead (not perfect but gets the job done)

**Comment by danielmarbach** [comment]
I tend to disagree. do we need a call?

**Comment by danielmarbach** [comment]
I agree that we went through effort to move it out of the core. But first
and foremost we are building APIs that should be convenient to use for our
customers. Since we already have features like around the gateway which
live in the core and stringly typed declare a dependency adding one more
would not spill over the water glass. But still it would make the usage
smoother.

 As a counter argument I would say an implicit feature that enabled itself
magically is hsrd to deprecate

**Comment by bording** [comment]
I suppose another option would be to remove support for replying with ints and enums! Then we'd definitely only need the package on the requesting side.

> Sneak the functionality into the core which silently behind the scenes enables itself when the callbacks feature is present

Thinking about this a bit more, how would this actually work? If we're saying that the package only needs to be installed on the requesting side, what would the replying side be using to trigger that it should turn on support?

If we're saying that the Callbacks package would have to be installed on the replying side anyway to know that Callbacks are enabled, then that's sort of defeating the point, because we'd be back to needing to move the instance discriminator check somewhere else anyway.

**Comment by andreasohlund** [comment]
Let's get on a call and hash this out?

**Comment by timbussmann** [comment]
> APIs that should be convenient to use for our customers.

I'd say having to configure an InstanceDiscriminator when it's not necessary, isn't a convenient API?

> Let's get on a call and hash this out?

:+1:

**Comment by bording** [comment]
@Particular/nservicebus-maintainers We still need to decide what change to make here to make this work better.

**Comment by danielmarbach** [comment]
@bording can you send an invite for a quick discussion next week?

**Comment by bording** [comment]
@Particular/nservicebus-maintainers I never managed to find a time where we could all meet to discuss this. Have we already declared this RC, or do we still have time to change something here?

**Comment by danielmarbach** [comment]
@andreasohlund pushed to myget.

**Comment by bording** [comment]
@danielmarbach Hmm, maybe we can still make a change here that would be ok after an RC?

**Comment by danielmarbach** [comment]
Talked to @andreasohlund and we are proposing to hold back with the changes. Yes it is inconvenient but not a major deal breaker. Our hope is to track how many people actually are using NServiceBus.Callbacks and it is OK to "punish" a little bit those users who are using it.

**Comment by danielmarbach** [comment]
Closed via https://github.com/Particular/NServiceBus.Callbacks/pull/62
