### ISSUE TITLE
Callback when cancelled immediately or right before token registration hangs forever

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Callbacks#40]
## Who's affected

All customers using callbacks with a cancellation token provided and if the cancellation token gets cancelled immediately or before the internal token registration.

## Symptoms

The callback will not be cancelled.

## Steps to reproduce

For immediate cancellation use:

```
    var cs = new CancellationTokenSource();
    cs.Cancel();
    var options = new SendOptions();
    await bus.Request<MyResponse>(new MyRequest(), options, cs.Token);
```

For before internal token registration use

```
    var cs = new CancellationTokenSource(TimeSpan.FromSeconds(1)); // or Milliseconds (exact time depending on transport and system used)
    var options = new SendOptions();
    await bus.Request<MyResponse>(new MyRequest(), options, cs.Token);
```

This one is hard to reproduce since it is a race.

## Analysis

* We need more early cancellation token exit points in the extension method `Request` and in the `UpdateRequestResponseCorrelationTableBehavior`
* There is a race in `UpdateRequestResponseCorrelationTableBehavior`. A cancellation token which is cancelled accepts a registration but immediately fires the registration. In that case the lambda inside the registration tries to cancel the response state but it can't since the state lookup has not yet registered it.

## Fix
* Change order of `lookup.RegisterState `and `requestResponseState.Register`
* Add early exit with `cancellationToken.ThrowIfCancellationRequested `before `RegisterState`, after `Register` and in the `Request` extension method.
* Challenges: Timing. Simplest "way" is to hack `RequestResponseStateLookup `to simulate those situation in a test.

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers ok if I do it right away?

**Comment by timbussmann** [comment]
@danielmarbach 👍 
is this a release blocker?

**Comment by danielmarbach** [comment]
I'd say yes since it practically does not work if the cancellation period is zero or short enough

**Comment by andreasohlund** [comment]
Since this can hang I'd say lets fix it given how hard this stuff is to troubleshoot in production

**Comment by danielmarbach** [comment]
PR is ready for review https://github.com/Particular/NServiceBus.Callbacks/issues/41

**Comment by timbussmann** [comment]
closing this as #41 has been merged.
