### ISSUE TITLE
Provide an easy way to unit test code that uses callbacks

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Callbacks#48]
It is currently hard to unit test code that is using callbacks as it is required to create a custom mock:

Sample using NSubstitute, as is shared on our google group.
```c#
messageSession.When(x=> x.Send(msg, Arg.Any<SendOptions>())).Do(call =>
            {
                var opts = call.Arg<SendOptions>();

                //need to workaround some nsb internals here using reflection
                object responseStateObj;
                if (opts.GetExtensions().TryGet("NServiceBus.RequestResponseStateLookup+State", out responseStateObj))
                {
                    var taskAdapter = responseStateObj.GetType().GetField("TaskCompletionSource")?.GetValue(responseStateObj);
                    Assert.NotNull(taskAdapter, "TaskCompletionSource field missing from adapter");
                    var setResultMethod = taskAdapter.GetType().GetMethod("TrySetResult");
                    Assert.NotNull(setResultMethod, "TrySetResult not found on " + taskAdapter.GetType());
                    setResultMethod.Invoke(taskAdapter, new object[] {response});
                }
                else
                {
                    Assert.Fail("Can not find expected response state: NServiceBus.RequestResponseStateLookup+State");
                }
            });
```

Source: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/PNu6mKh9BUE/tMmPGFI1AAAJ

**Comment by timbussmann** [comment]
@ramonsmits any API proposals?

**Comment by danielmarbach** [comment]
Would we want to create extensions as a dedicated package called NServiceBus.Callbacks.Testing which references the NServiceBus.Testing package?

**Comment by ramonsmits** [comment]
@timbussmann Well, the customer would probably be very welcome with a visibility change on the type `NServiceBus.RequestResponseStateLookup+State` to make that code a bit shorter and easier to read.

* https://github.com/Particular/NServiceBus.Callbacks/blob/1.0.0/src/NServiceBus.Callbacks/RequestResponseStateLookup.cs#L31

To make callbacks testable we probably require a framework just as with sagas and handlers but then to create a sort of callback scenario.

**Comment by timbussmann** [comment]
> Would we want to create extensions as a dedicated package called NServiceBus.Callbacks.Testing which references the NServiceBus.Testing package?

not a big fan of a testing package for each downstream repository but not sure whether there is an alternative.

> very welcome with a visibility change on the type NServiceBus.RequestResponseStateLookup+State

that doesn't sound like an easy to use API to me, rather like a workaround?

**Comment by ramonsmits** [comment]
@timbussmann It's a workaround for not having a testing framework. I'm looking at the extension methods and all lead to 1 method that you would need to mock. I'm not sure if creating a testing framework is really needed if just exposing these type will make it pretty easy to mock the results.

Its two types that would need to become public:

* RequestResponseStateLookup.State
* TaskCompletionSourceAdapter


This is the code needed to mock the results compared to the code in the issue description if those types would be visible:

```c#
var session = Substitute.For<IMessageSession>();

session.When(x => x.Send(Arg.Any<object>(), Arg.Any<SendOptions>())).Do(call =>
{
    var opts = call.Arg<SendOptions>();
    opts.GetExtensions().Get<RequestResponseStateLookup.State>().TaskCompletionSource.TrySetResult(42);
});
```

But what about adding this simple extension method?

```c#
public static class CallbackTestExtensions
{
    public static void SetResult(this SendOptions opts, object result)
    {
        opts.GetExtensions().Get<RequestResponseStateLookup.State>().TaskCompletionSource.TrySetResult(result);
    }
}
```

With this we don't need to expose the previous mentioned types and you would get the following mock code:

```c#
var session = Substitute.For<IMessageSession>();

session.When(x => x.Send(Arg.Any<object>(), Arg.Any<SendOptions>())).Do(call =>
{
    var opts = call.Arg<SendOptions>();
    opts.SetResult(42);
});
```


That extension could either be put in `NServiceBus.Callbacks` as I don't think it is worth it to put this in a separate assembly.

**Comment by feinoujc** [comment]
Creating an extension method that let's you drill into the internals and set the result seems like a good option to me, all things considered

(I am original author of this issue)

**Comment by danielmarbach** [comment]
@feinoujc @ramonsmits I raised a simple spike https://github.com/Particular/NServiceBus.Callbacks/pull/50 What do you think?

**Comment by danielmarbach** [comment]
#50 has been merged. Closing
