### ISSUE TITLE
When_a_callback_for_local_message_canceled.ShouldNot_trigger_the_callback_when_canceled fails from time to time

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Callbacks#78]
See https://github.com/Particular/NServiceBus.Callbacks/pull/76#issuecomment-334826218

**Comment by bording** [comment]
FYI, this test is still appears to be flaky.

**Comment by andreasohlund** [comment]
I've seen the same thing locally, will investigate
