### ISSUE TITLE
Allow to opt-out from uniquely addressable constraint

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Callbacks#79]
Raised in https://discuss.particular.net/t/how-do-i-configure-iis-for-use-with-callbacks/131

It makes sense by default to enforce in callbacks that an endpoint needs to be uniquely addressable. Since callbacks can be used with any transport. When a transport by default uses competing consumer a uniquely addressable queue is required for the replies. 

For MSMQ though that restriction is unnecessary since the combination of `queue@machine` name is already a unique combination as long as the same endpoint is not run multiple times on the same machine.

**Comment by andreasohlund** [comment]
Fixed in #80

**Comment by andreasohlund** [comment]
Closing this as won't fix

See https://discuss.particular.net/t/how-do-i-configure-iis-for-use-with-callbacks/131/12
